apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: {{ .Values.configMapPostgres.postgresDB }}
  POSTGRES_USER: {{ .Values.configMapPostgres.postgresUSER }}
  POSTGRES_PASSWORD: {{ .Values.configMapPostgres.postgresPASSWORD }}